redhat/configs: automotive: disable CONFIG_CRYPTO_DEV_VIRTIO
In kernel-5.14.0-592.el9, c045e0980eb36 ('Merge: pcrypto/tegra: pull in
fixes for Tegra Security Engine Driver') was merged which caused the
following build error since this config is enabled in automotive.
Thus, CONFIG_CRYPTO_DEV_VIRTIO will be disabled for now.

00:06:41 drivers/crypto/virtio/virtio_crypto_algs.c: In function ‘virtio_crypto_skcipher_init’:
00:06:41 drivers/crypto/virtio/virtio_crypto_algs.c:540:26: error: ‘struct crypto_engine_op’ has no member named ‘prepare_request’
00:06:41   540 |         ctx->enginectx.op.prepare_request = NULL;
00:06:41       |                          ^
00:06:41 drivers/crypto/virtio/virtio_crypto_algs.c:541:26: error: ‘struct crypto_engine_op’ has no member named ‘unprepare_request’
00:06:41   541 |         ctx->enginectx.op.unprepare_request = NULL;

Signed-off-by: Scott Weaver <scweaver@redhat.com>